### ISSUE TITLE
v1.5.0 does not work with solr-5.4.0.zip - ClassNotFoundException

### ISSUE THREAD

**Issue by magicdude4eva** [kohesive/solr-undertow#27]
Getting the following error on v1.5.0:
```
2016-01-21 11:13:16.630 [      main] [          ] WARN  SolrServer -   jar:file:/home/prodza/undertow/solr-wars/solr-5.4.0.zip
2016-01-21 11:13:16.731 [      main] [          ] WARN  SolrServer -   jar:file:/home/prodza/undertow/solr-wars/solr-5.4.0.zip!/solr-5.4.0/server/solr-webapp/webapp
2016-01-21 11:13:17.541 [      main] [          ] ERROR SolrServer - Server unhandled exception during startup 'org.apache.solr.servlet.ZookeeperInfoServlet'
java.lang.ClassNotFoundException: org.apache.solr.servlet.ZookeeperInfoServlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_72]
	at org.bremeld.solr.undertow.Server.buildSolrServletHandler(SolrUndertow.kt:334) ~[solr-undertow-1.5.0.jar:na]
	at org.bremeld.solr.undertow.Server.run(SolrUndertow.kt:79) ~[solr-undertow-1.5.0.jar:na]
	at org.bremeld.solr.undertow.AppKt.main(App.kt:42) [solr-undertow-1.5.0.jar:na]
	at org.bremeld.solr.undertow.UndertowPackage.main(Unknown Source) [solr-undertow-1.5.0.jar:na]
```

The extracted jars for 5.4.0 do not contain the servlet:
```
find -name "*.jar" | xargs -n 1 jar tf | grep -i ZookeeperInfo
```

However 5.2.1 does:
```
[prodza@zasolrm01 lib]$ find -name "*.jar" | xargs -n 1 jar tf | grep -i ZookeeperInfo
org/apache/solr/servlet/ZookeeperInfoServlet$FilterType.class
org/apache/solr/servlet/ZookeeperInfoServlet$PageOfCollections.class
org/apache/solr/servlet/ZookeeperInfoServlet$PagedCollectionSupport.class
org/apache/solr/servlet/ZookeeperInfoServlet$ZKPrinter.class
org/apache/solr/servlet/ZookeeperInfoServlet.class
```

**Comment by OsamaAbbas** [comment]
Any plans to fix this issue? Same in solr 5.4.1.

**Comment by apatrida** [comment]
yes, I already have this fixed in my current version, can release soon

**Comment by OsamaAbbas** [comment]
Thank you!

**Comment by magicdude4eva** [comment]
Awesome! Thank you. From personal experience did you find that the bundled Solr-zip (any version from 5.3.x onwards) seems to perform worse/slower than 5.2.1?

**Comment by OsamaAbbas** [comment]
I suggest to specify (maybe in README file) which files inside solr-x.x.x.zip are required, so that we can safely remove the other files. I guess this will reduce this huge file from +130Mb to ~30Mb or ~40Mb.

**Comment by apatrida** [comment]
Fixed in 1.6.0-BETA-1
https://github.com/kohesive/solr-undertow/releases/tag/v1.6.0-BETA-1

Uploading other variations now to that release, but you can add your own solr zip file and get started testing.

**Comment by apatrida** [comment]
@OsamaAbbas adding that now.

**Comment by magicdude4eva** [comment]
Thank you, will give it a run under production load in the next few days. Solr 5.4.0 on Jetty was horrible (and Solr 5.3.x onwards on Undertow as well). I am hoping that perhaps performance is improved with this built but somehow doubt it.

@apatrida - Is there any merit to be on undertow 1.6.0 over 1.5.0 when running Solr 5.2.1 (we are using JDK1.8 with G1GC)?

**Comment by apatrida** [comment]
@magicdude4eva If there is a performance difference it would be internal to Solr, haven't tracked enough commits on 5.x to know what would slow it down.  Did you file an issue in the Solr JIRA or the user mailing list?

1.6.0 doesn't add anything for Solr 5.2.1, so you are fine staying back with 1.5.0.  Currently 1.6.0 adds risk because it isn't tested in production (by me) although it should be fine, it needs some supervision to be sure.
